// AUTO-GENERATED by scripts/generate-tambo-ui-catalog.mjs
// Do not edit manually. Re-run: node scripts/generate-tambo-ui-catalog.mjs

export const SITE_UI_COMPONENT_CATALOG = [
  {
    "name": "accordion",
    "purpose": "UI component from components ui accordion",
    "source": "components/ui/accordion.tsx"
  },
  {
    "name": "AdminDashboardPage",
    "purpose": "UI component from components admin AdminDashboardPage",
    "source": "components/admin/AdminDashboardPage.tsx"
  },
  {
    "name": "AdminsTab",
    "purpose": "UI component from components admin dashboard tabs content AdminsTab",
    "source": "components/admin/dashboard/tabs-content/AdminsTab.tsx"
  },
  {
    "name": "alert",
    "purpose": "UI component from components ui alert",
    "source": "components/ui/alert.tsx"
  },
  {
    "name": "alert-dialog",
    "purpose": "UI component from components ui alert dialog",
    "source": "components/ui/alert-dialog.tsx"
  },
  {
    "name": "AllowedTabsPicker",
    "purpose": "UI component from components admin dashboard AllowedTabsPicker",
    "source": "components/admin/dashboard/AllowedTabsPicker.tsx"
  },
  {
    "name": "animated-input",
    "purpose": "UI component from components smoothui smoothui animated input index",
    "source": "components/smoothui/smoothui/animated-input/index.tsx"
  },
  {
    "name": "aspect-ratio",
    "purpose": "UI component from components ui aspect ratio",
    "source": "components/ui/aspect-ratio.tsx"
  },
  {
    "name": "AuthShell",
    "purpose": "UI component from components auth AuthShell",
    "source": "components/auth/AuthShell.tsx"
  },
  {
    "name": "avatar",
    "purpose": "UI component from components ui avatar",
    "source": "components/ui/avatar.tsx"
  },
  {
    "name": "badge",
    "purpose": "UI component from components ui badge",
    "source": "components/ui/badge.tsx"
  },
  {
    "name": "basic-dropdown",
    "purpose": "UI component from components smoothui smoothui basic dropdown index",
    "source": "components/smoothui/smoothui/basic-dropdown/index.tsx"
  },
  {
    "name": "basic-modal",
    "purpose": "UI component from components smoothui smoothui basic modal index",
    "source": "components/smoothui/smoothui/basic-modal/index.tsx"
  },
  {
    "name": "BranchesPage",
    "purpose": "UI component from components pos branches BranchesPage",
    "source": "components/pos/branches/BranchesPage.tsx"
  },
  {
    "name": "breadcrumb",
    "purpose": "UI component from components ui breadcrumb",
    "source": "components/ui/breadcrumb.tsx"
  },
  {
    "name": "button",
    "purpose": "UI component from components ui button",
    "source": "components/ui/button.tsx"
  },
  {
    "name": "calendar",
    "purpose": "UI component from components ui calendar",
    "source": "components/ui/calendar.tsx"
  },
  {
    "name": "CalendarDateSelector",
    "purpose": "UI component from components admin dashboard shared CalendarDateSelector",
    "source": "components/admin/dashboard/shared/CalendarDateSelector.tsx"
  },
  {
    "name": "CalendarRangeSelector",
    "purpose": "UI component from components admin dashboard shared CalendarRangeSelector",
    "source": "components/admin/dashboard/shared/CalendarRangeSelector.tsx"
  },
  {
    "name": "CalendarView",
    "purpose": "UI component from components CalendarView",
    "source": "components/CalendarView.tsx"
  },
  {
    "name": "CameraScanner",
    "purpose": "UI component from components pos terminal CameraScanner",
    "source": "components/pos/terminal/CameraScanner.tsx"
  },
  {
    "name": "card",
    "purpose": "UI component from components ui card",
    "source": "components/ui/card.tsx"
  },
  {
    "name": "carousel",
    "purpose": "UI component from components ui carousel",
    "source": "components/ui/carousel.tsx"
  },
  {
    "name": "CartPanel",
    "purpose": "UI component from components pos terminal CartPanel",
    "source": "components/pos/terminal/CartPanel.tsx"
  },
  {
    "name": "CategoriesManagerPage",
    "purpose": "UI component from components pos products CategoriesManagerPage",
    "source": "components/pos/products/CategoriesManagerPage.tsx"
  },
  {
    "name": "ChangePasswordModal",
    "purpose": "UI component from components admin ChangePasswordModal",
    "source": "components/admin/ChangePasswordModal.tsx"
  },
  {
    "name": "chart",
    "purpose": "UI component from components ui chart",
    "source": "components/ui/chart.tsx"
  },
  {
    "name": "ChatCenter",
    "purpose": "UI component from components chat ChatCenter",
    "source": "components/chat/ChatCenter.tsx"
  },
  {
    "name": "ChatInterface",
    "purpose": "UI component from components ai ChatInterface",
    "source": "components/ai/ChatInterface.tsx"
  },
  {
    "name": "ChatTab",
    "purpose": "UI component from components chat ChatTab",
    "source": "components/chat/ChatTab.tsx"
  },
  {
    "name": "ChatUnifiedTab",
    "purpose": "UI component from components chat ChatUnifiedTab",
    "source": "components/chat/ChatUnifiedTab.tsx"
  },
  {
    "name": "checkbox",
    "purpose": "UI component from components ui checkbox",
    "source": "components/ui/checkbox.tsx"
  },
  {
    "name": "collapsible",
    "purpose": "UI component from components ui collapsible",
    "source": "components/ui/collapsible.tsx"
  },
  {
    "name": "command",
    "purpose": "UI component from components ui command",
    "source": "components/ui/command.tsx"
  },
  {
    "name": "CommandPalette",
    "purpose": "UI component from components layout CommandPalette",
    "source": "components/layout/CommandPalette.tsx"
  },
  {
    "name": "context-menu",
    "purpose": "UI component from components ui context menu",
    "source": "components/ui/context-menu.tsx"
  },
  {
    "name": "CookingManager",
    "purpose": "UI component from components admin warehouse CookingManager",
    "source": "components/admin/warehouse/CookingManager.tsx"
  },
  {
    "name": "CourierMap",
    "purpose": "UI component from components courier CourierMap",
    "source": "components/courier/CourierMap.tsx"
  },
  {
    "name": "CourierProfile",
    "purpose": "UI component from components courier CourierProfile",
    "source": "components/courier/CourierProfile.tsx"
  },
  {
    "name": "Cursors",
    "purpose": "UI component from components collaboration Cursors",
    "source": "components/collaboration/Cursors.tsx"
  },
  {
    "name": "CustomerDisplayPage",
    "purpose": "UI component from components pos customer display CustomerDisplayPage",
    "source": "components/pos/customer-display/CustomerDisplayPage.tsx"
  },
  {
    "name": "CustomerPickerDialog",
    "purpose": "UI component from components pos terminal CustomerPickerDialog",
    "source": "components/pos/terminal/CustomerPickerDialog.tsx"
  },
  {
    "name": "DesktopTabsNav",
    "purpose": "UI component from components admin dashboard DesktopTabsNav",
    "source": "components/admin/dashboard/DesktopTabsNav.tsx"
  },
  {
    "name": "dialog",
    "purpose": "UI component from components ui dialog",
    "source": "components/ui/dialog.tsx"
  },
  {
    "name": "DiscountsPage",
    "purpose": "UI component from components pos discounts DiscountsPage",
    "source": "components/pos/discounts/DiscountsPage.tsx"
  },
  {
    "name": "DishesManager",
    "purpose": "UI component from components admin warehouse DishesManager",
    "source": "components/admin/warehouse/DishesManager.tsx"
  },
  {
    "name": "DispatchLeafletMap",
    "purpose": "UI component from components admin orders DispatchLeafletMap",
    "source": "components/admin/orders/DispatchLeafletMap.tsx"
  },
  {
    "name": "DispatchMapPanel",
    "purpose": "UI component from components admin orders DispatchMapPanel",
    "source": "components/admin/orders/DispatchMapPanel.tsx"
  },
  {
    "name": "drawer",
    "purpose": "UI component from components ui drawer",
    "source": "components/ui/drawer.tsx"
  },
  {
    "name": "dropdown-menu",
    "purpose": "UI component from components ui dropdown menu",
    "source": "components/ui/dropdown-menu.tsx"
  },
  {
    "name": "EmployeesPage",
    "purpose": "UI component from components pos employees EmployeesPage",
    "source": "components/pos/employees/EmployeesPage.tsx"
  },
  {
    "name": "EntityStatusBadge",
    "purpose": "UI component from components admin dashboard shared EntityStatusBadge",
    "source": "components/admin/dashboard/shared/EntityStatusBadge.tsx"
  },
  {
    "name": "excel",
    "purpose": "UI component from components excel index",
    "source": "components/excel/index.ts"
  },
  {
    "name": "ExcelEditor",
    "purpose": "UI component from components excel ExcelEditor",
    "source": "components/excel/ExcelEditor.tsx"
  },
  {
    "name": "FeaturesTab",
    "purpose": "UI component from components admin features FeaturesTab",
    "source": "components/admin/features/FeaturesTab.tsx"
  },
  {
    "name": "FilterToolbar",
    "purpose": "UI component from components admin dashboard shared FilterToolbar",
    "source": "components/admin/dashboard/shared/FilterToolbar.tsx"
  },
  {
    "name": "FinanceTab",
    "purpose": "UI component from components admin FinanceTab",
    "source": "components/admin/FinanceTab.tsx"
  },
  {
    "name": "form",
    "purpose": "UI component from components ui form",
    "source": "components/ui/form.tsx"
  },
  {
    "name": "FormField",
    "purpose": "UI component from components admin dashboard shared FormField",
    "source": "components/admin/dashboard/shared/FormField.tsx"
  },
  {
    "name": "GiftCardsPage",
    "purpose": "UI component from components pos gift cards GiftCardsPage",
    "source": "components/pos/gift-cards/GiftCardsPage.tsx"
  },
  {
    "name": "GourmetButton",
    "purpose": "UI component from components GourmetButton",
    "source": "components/GourmetButton.tsx"
  },
  {
    "name": "GourmetCard",
    "purpose": "UI component from components GourmetCard",
    "source": "components/GourmetCard.tsx"
  },
  {
    "name": "HistoryTable",
    "purpose": "UI component from components admin HistoryTable",
    "source": "components/admin/HistoryTable.tsx"
  },
  {
    "name": "hover-card",
    "purpose": "UI component from components ui hover card",
    "source": "components/ui/hover-card.tsx"
  },
  {
    "name": "icon-button",
    "purpose": "UI component from components ui icon button",
    "source": "components/ui/icon-button.tsx"
  },
  {
    "name": "IngredientsManager",
    "purpose": "UI component from components admin warehouse IngredientsManager",
    "source": "components/admin/warehouse/IngredientsManager.tsx"
  },
  {
    "name": "input",
    "purpose": "UI component from components ui input",
    "source": "components/ui/input.tsx"
  },
  {
    "name": "input-otp",
    "purpose": "UI component from components ui input otp",
    "source": "components/ui/input-otp.tsx"
  },
  {
    "name": "InterfaceSettings",
    "purpose": "UI component from components admin InterfaceSettings",
    "source": "components/admin/InterfaceSettings.tsx"
  },
  {
    "name": "InventoryPage",
    "purpose": "UI component from components pos inventory InventoryPage",
    "source": "components/pos/inventory/InventoryPage.tsx"
  },
  {
    "name": "KDSPage",
    "purpose": "UI component from components pos kds KDSPage",
    "source": "components/pos/kds/KDSPage.tsx"
  },
  {
    "name": "label",
    "purpose": "UI component from components ui label",
    "source": "components/ui/label.tsx"
  },
  {
    "name": "LanguageSwitcher",
    "purpose": "UI component from components LanguageSwitcher",
    "source": "components/LanguageSwitcher.tsx"
  },
  {
    "name": "LiveStrip",
    "purpose": "UI component from components pos dashboard LiveStrip",
    "source": "components/pos/dashboard/LiveStrip.tsx"
  },
  {
    "name": "LoyaltyPage",
    "purpose": "UI component from components pos loyalty LoyaltyPage",
    "source": "components/pos/loyalty/LoyaltyPage.tsx"
  },
  {
    "name": "menubar",
    "purpose": "UI component from components ui menubar",
    "source": "components/ui/menubar.tsx"
  },
  {
    "name": "MiddleLiveMap",
    "purpose": "UI component from components admin orders MiddleLiveMap",
    "source": "components/admin/orders/MiddleLiveMap.tsx"
  },
  {
    "name": "MiniLocationPickerMap",
    "purpose": "UI component from components admin dashboard shared MiniLocationPickerMap",
    "source": "components/admin/dashboard/shared/MiniLocationPickerMap.tsx"
  },
  {
    "name": "MobileBottomTabsNav",
    "purpose": "UI component from components admin dashboard MobileBottomTabsNav",
    "source": "components/admin/dashboard/MobileBottomTabsNav.tsx"
  },
  {
    "name": "MobileTabIndicator",
    "purpose": "UI component from components MobileTabIndicator",
    "source": "components/MobileTabIndicator.tsx"
  },
  {
    "name": "navigation-menu",
    "purpose": "UI component from components ui navigation menu",
    "source": "components/ui/navigation-menu.tsx"
  },
  {
    "name": "number-flow",
    "purpose": "UI component from components smoothui smoothui number flow index",
    "source": "components/smoothui/smoothui/number-flow/index.tsx"
  },
  {
    "name": "OrderModal",
    "purpose": "UI component from components admin dashboard modals OrderModal",
    "source": "components/admin/dashboard/modals/OrderModal.tsx"
  },
  {
    "name": "OrdersHistoryPage",
    "purpose": "UI component from components pos orders OrdersHistoryPage",
    "source": "components/pos/orders/OrdersHistoryPage.tsx"
  },
  {
    "name": "OrdersTable",
    "purpose": "UI component from components admin OrdersTable",
    "source": "components/admin/OrdersTable.tsx"
  },
  {
    "name": "OtpAuthForm",
    "purpose": "UI component from components site OtpAuthForm",
    "source": "components/site/OtpAuthForm.tsx"
  },
  {
    "name": "pagination",
    "purpose": "UI component from components ui pagination",
    "source": "components/ui/pagination.tsx"
  },
  {
    "name": "PaymentDialog",
    "purpose": "UI component from components pos terminal PaymentDialog",
    "source": "components/pos/terminal/PaymentDialog.tsx"
  },
  {
    "name": "popover",
    "purpose": "UI component from components ui popover",
    "source": "components/ui/popover.tsx"
  },
  {
    "name": "POSDashboardPage",
    "purpose": "UI component from components pos dashboard POSDashboardPage",
    "source": "components/pos/dashboard/POSDashboardPage.tsx"
  },
  {
    "name": "POSTerminalPage",
    "purpose": "UI component from components pos terminal POSTerminalPage",
    "source": "components/pos/terminal/POSTerminalPage.tsx"
  },
  {
    "name": "PrintersPage",
    "purpose": "UI component from components pos printers PrintersPage",
    "source": "components/pos/printers/PrintersPage.tsx"
  },
  {
    "name": "ProductDetailDialog",
    "purpose": "UI component from components pos terminal ProductDetailDialog",
    "source": "components/pos/terminal/ProductDetailDialog.tsx"
  },
  {
    "name": "ProductGrid",
    "purpose": "UI component from components pos terminal ProductGrid",
    "source": "components/pos/terminal/ProductGrid.tsx"
  },
  {
    "name": "ProductsManagerPage",
    "purpose": "UI component from components pos products ProductsManagerPage",
    "source": "components/pos/products/ProductsManagerPage.tsx"
  },
  {
    "name": "progress",
    "purpose": "UI component from components ui progress",
    "source": "components/ui/progress.tsx"
  },
  {
    "name": "PWAInstallPrompt",
    "purpose": "UI component from components PWAInstallPrompt",
    "source": "components/PWAInstallPrompt.tsx"
  },
  {
    "name": "PWANetworkStatus",
    "purpose": "UI component from components PWANetworkStatus",
    "source": "components/PWANetworkStatus.tsx"
  },
  {
    "name": "radio-group",
    "purpose": "UI component from components ui radio group",
    "source": "components/ui/radio-group.tsx"
  },
  {
    "name": "RefreshIconButton",
    "purpose": "UI component from components admin dashboard shared RefreshIconButton",
    "source": "components/admin/dashboard/shared/RefreshIconButton.tsx"
  },
  {
    "name": "ReportsPage",
    "purpose": "UI component from components pos reports ReportsPage",
    "source": "components/pos/reports/ReportsPage.tsx"
  },
  {
    "name": "ReservationsPage",
    "purpose": "UI component from components pos reservations ReservationsPage",
    "source": "components/pos/reservations/ReservationsPage.tsx"
  },
  {
    "name": "resizable",
    "purpose": "UI component from components ui resizable",
    "source": "components/ui/resizable.tsx"
  },
  {
    "name": "right-action-line",
    "purpose": "UI component from components ui right action line",
    "source": "components/ui/right-action-line.tsx"
  },
  {
    "name": "RouteOptimizeButton",
    "purpose": "UI component from components admin RouteOptimizeButton",
    "source": "components/admin/RouteOptimizeButton.tsx"
  },
  {
    "name": "scroll-area",
    "purpose": "UI component from components ui scroll area",
    "source": "components/ui/scroll-area.tsx"
  },
  {
    "name": "search-panel",
    "purpose": "UI component from components ui search panel",
    "source": "components/ui/search-panel.tsx"
  },
  {
    "name": "SectionMetrics",
    "purpose": "UI component from components admin dashboard shared SectionMetrics",
    "source": "components/admin/dashboard/shared/SectionMetrics.tsx"
  },
  {
    "name": "select",
    "purpose": "UI component from components ui select",
    "source": "components/ui/select.tsx"
  },
  {
    "name": "separator",
    "purpose": "UI component from components ui separator",
    "source": "components/ui/separator.tsx"
  },
  {
    "name": "ServiceWorkerRegistration",
    "purpose": "UI component from components ServiceWorkerRegistration",
    "source": "components/ServiceWorkerRegistration.tsx"
  },
  {
    "name": "SessionProviderClient",
    "purpose": "UI component from components providers SessionProviderClient",
    "source": "components/providers/SessionProviderClient.tsx"
  },
  {
    "name": "SetsTab",
    "purpose": "UI component from components admin SetsTab",
    "source": "components/admin/SetsTab.tsx"
  },
  {
    "name": "SettingsPage",
    "purpose": "UI component from components pos settings SettingsPage",
    "source": "components/pos/settings/SettingsPage.tsx"
  },
  {
    "name": "sheet",
    "purpose": "UI component from components ui sheet",
    "source": "components/ui/sheet.tsx"
  },
  {
    "name": "Sheet",
    "purpose": "UI component from components excel Sheet",
    "source": "components/excel/Sheet.tsx"
  },
  {
    "name": "ShiftPage",
    "purpose": "UI component from components pos shift ShiftPage",
    "source": "components/pos/shift/ShiftPage.tsx"
  },
  {
    "name": "sidebar",
    "purpose": "UI component from components ui sidebar",
    "source": "components/ui/sidebar.tsx"
  },
  {
    "name": "SiteAuthShell",
    "purpose": "UI component from components site SiteAuthShell",
    "source": "components/site/SiteAuthShell.tsx"
  },
  {
    "name": "SiteBuilderCard",
    "purpose": "UI component from components admin SiteBuilderCard",
    "source": "components/admin/SiteBuilderCard.tsx"
  },
  {
    "name": "SiteContent",
    "purpose": "UI component from components site SiteContent",
    "source": "components/site/SiteContent.tsx"
  },
  {
    "name": "SiteScaffold",
    "purpose": "UI component from components site SiteScaffold",
    "source": "components/site/SiteScaffold.tsx"
  },
  {
    "name": "SiteStyleRendersDialog",
    "purpose": "UI component from components admin SiteStyleRendersDialog",
    "source": "components/admin/SiteStyleRendersDialog.tsx"
  },
  {
    "name": "skeleton",
    "purpose": "UI component from components ui skeleton",
    "source": "components/ui/skeleton.tsx"
  },
  {
    "name": "slider",
    "purpose": "UI component from components ui slider",
    "source": "components/ui/slider.tsx"
  },
  {
    "name": "smoothui",
    "purpose": "UI component from components smoothui index",
    "source": "components/smoothui/index.ts"
  },
  {
    "name": "sonner",
    "purpose": "UI component from components ui sonner",
    "source": "components/ui/sonner.tsx"
  },
  {
    "name": "StatsCards",
    "purpose": "UI component from components admin StatsCards",
    "source": "components/admin/StatsCards.tsx"
  },
  {
    "name": "SuppliersPage",
    "purpose": "UI component from components pos suppliers SuppliersPage",
    "source": "components/pos/suppliers/SuppliersPage.tsx"
  },
  {
    "name": "switch",
    "purpose": "UI component from components ui switch",
    "source": "components/ui/switch.tsx"
  },
  {
    "name": "TabBar",
    "purpose": "UI component from components excel TabBar",
    "source": "components/excel/TabBar.tsx"
  },
  {
    "name": "TabEmptyState",
    "purpose": "UI component from components admin dashboard shared TabEmptyState",
    "source": "components/admin/dashboard/shared/TabEmptyState.tsx"
  },
  {
    "name": "table",
    "purpose": "UI component from components ui table",
    "source": "components/ui/table.tsx"
  },
  {
    "name": "TablePickerDialog",
    "purpose": "UI component from components pos terminal TablePickerDialog",
    "source": "components/pos/terminal/TablePickerDialog.tsx"
  },
  {
    "name": "TablesPage",
    "purpose": "UI component from components pos tables TablesPage",
    "source": "components/pos/tables/TablesPage.tsx"
  },
  {
    "name": "tabMeta",
    "purpose": "UI component from components admin dashboard tabMeta",
    "source": "components/admin/dashboard/tabMeta.ts"
  },
  {
    "name": "tabs",
    "purpose": "UI component from components admin dashboard tabs",
    "source": "components/admin/dashboard/tabs.ts"
  },
  {
    "name": "tabs",
    "purpose": "UI component from components ui tabs",
    "source": "components/ui/tabs.tsx"
  },
  {
    "name": "TamboAgentWidget",
    "purpose": "UI component from components tambo TamboAgentWidget",
    "source": "components/tambo/TamboAgentWidget.tsx"
  },
  {
    "name": "TamboProviderClient",
    "purpose": "UI component from components providers TamboProviderClient",
    "source": "components/providers/TamboProviderClient.tsx"
  },
  {
    "name": "textarea",
    "purpose": "UI component from components ui textarea",
    "source": "components/ui/textarea.tsx"
  },
  {
    "name": "TimeclockPage",
    "purpose": "UI component from components pos timeclock TimeclockPage",
    "source": "components/pos/timeclock/TimeclockPage.tsx"
  },
  {
    "name": "toast",
    "purpose": "UI component from components ui toast",
    "source": "components/ui/toast.tsx"
  },
  {
    "name": "toaster",
    "purpose": "UI component from components ui toaster",
    "source": "components/ui/toaster.tsx"
  },
  {
    "name": "TodaysMenu",
    "purpose": "UI component from components admin TodaysMenu",
    "source": "components/admin/TodaysMenu.tsx"
  },
  {
    "name": "toggle",
    "purpose": "UI component from components ui toggle",
    "source": "components/ui/toggle.tsx"
  },
  {
    "name": "toggle-group",
    "purpose": "UI component from components ui toggle group",
    "source": "components/ui/toggle-group.tsx"
  },
  {
    "name": "Toolbar",
    "purpose": "UI component from components excel Toolbar",
    "source": "components/excel/Toolbar.tsx"
  },
  {
    "name": "tooltip",
    "purpose": "UI component from components ui tooltip",
    "source": "components/ui/tooltip.tsx"
  },
  {
    "name": "TrialStatus",
    "purpose": "UI component from components admin TrialStatus",
    "source": "components/admin/TrialStatus.tsx"
  },
  {
    "name": "types",
    "purpose": "UI component from components admin dashboard types",
    "source": "components/admin/dashboard/types.ts"
  },
  {
    "name": "typewriter-text",
    "purpose": "UI component from components smoothui smoothui typewriter text index",
    "source": "components/smoothui/smoothui/typewriter-text/index.tsx"
  },
  {
    "name": "UnifiedShell",
    "purpose": "UI component from components layout UnifiedShell",
    "source": "components/layout/UnifiedShell.tsx"
  },
  {
    "name": "UnifiedSidebar",
    "purpose": "UI component from components layout UnifiedSidebar",
    "source": "components/layout/UnifiedSidebar.tsx"
  },
  {
    "name": "use-cart",
    "purpose": "UI component from components pos terminal use cart",
    "source": "components/pos/terminal/use-cart.ts"
  },
  {
    "name": "useDashboardData",
    "purpose": "UI component from components admin dashboard useDashboardData",
    "source": "components/admin/dashboard/useDashboardData.ts"
  },
  {
    "name": "UserGuide",
    "purpose": "UI component from components UserGuide",
    "source": "components/UserGuide.tsx"
  },
  {
    "name": "UserList",
    "purpose": "UI component from components collaboration UserList",
    "source": "components/collaboration/UserList.tsx"
  },
  {
    "name": "WarehouseStartPointPickerMap",
    "purpose": "UI component from components admin dashboard shared WarehouseStartPointPickerMap",
    "source": "components/admin/dashboard/shared/WarehouseStartPointPickerMap.tsx"
  },
  {
    "name": "WarehouseTab",
    "purpose": "UI component from components admin WarehouseTab",
    "source": "components/admin/WarehouseTab.tsx"
  }
] as const;

export const SITE_UI_PAGE_CATALOG = [
  {
    "path": "/",
    "purpose": "Interactive page at /"
  },
  {
    "path": "/auth/redirect",
    "purpose": "Interactive page at /auth/redirect"
  },
  {
    "path": "/courier",
    "purpose": "Interactive page at /courier"
  },
  {
    "path": "/login",
    "purpose": "Interactive page at /login"
  },
  {
    "path": "/low-admin",
    "purpose": "Interactive page at /low-admin"
  },
  {
    "path": "/middle-admin",
    "purpose": "Interactive page at /middle-admin"
  },
  {
    "path": "/middle-admin/database",
    "purpose": "Interactive page at /middle-admin/database"
  },
  {
    "path": "/offline",
    "purpose": "Interactive page at /offline"
  },
  {
    "path": "/pos",
    "purpose": "Interactive page at /pos"
  },
  {
    "path": "/pos/branches",
    "purpose": "Interactive page at /pos/branches"
  },
  {
    "path": "/pos/categories",
    "purpose": "Interactive page at /pos/categories"
  },
  {
    "path": "/pos/customer-display",
    "purpose": "Interactive page at /pos/customer-display"
  },
  {
    "path": "/pos/dashboard",
    "purpose": "Interactive page at /pos/dashboard"
  },
  {
    "path": "/pos/discounts",
    "purpose": "Interactive page at /pos/discounts"
  },
  {
    "path": "/pos/employees",
    "purpose": "Interactive page at /pos/employees"
  },
  {
    "path": "/pos/gift-cards",
    "purpose": "Interactive page at /pos/gift-cards"
  },
  {
    "path": "/pos/inventory",
    "purpose": "Interactive page at /pos/inventory"
  },
  {
    "path": "/pos/kds",
    "purpose": "Interactive page at /pos/kds"
  },
  {
    "path": "/pos/loyalty",
    "purpose": "Interactive page at /pos/loyalty"
  },
  {
    "path": "/pos/orders",
    "purpose": "Interactive page at /pos/orders"
  },
  {
    "path": "/pos/printers",
    "purpose": "Interactive page at /pos/printers"
  },
  {
    "path": "/pos/products",
    "purpose": "Interactive page at /pos/products"
  },
  {
    "path": "/pos/reports",
    "purpose": "Interactive page at /pos/reports"
  },
  {
    "path": "/pos/reservations",
    "purpose": "Interactive page at /pos/reservations"
  },
  {
    "path": "/pos/settings",
    "purpose": "Interactive page at /pos/settings"
  },
  {
    "path": "/pos/shift",
    "purpose": "Interactive page at /pos/shift"
  },
  {
    "path": "/pos/suppliers",
    "purpose": "Interactive page at /pos/suppliers"
  },
  {
    "path": "/pos/tables",
    "purpose": "Interactive page at /pos/tables"
  },
  {
    "path": "/pos/terminal",
    "purpose": "Interactive page at /pos/terminal"
  },
  {
    "path": "/pos/timeclock",
    "purpose": "Interactive page at /pos/timeclock"
  },
  {
    "path": "/signup",
    "purpose": "Interactive page at /signup"
  },
  {
    "path": "/sites/[subdomain]",
    "purpose": "Interactive page at /sites/[subdomain]"
  },
  {
    "path": "/sites/[subdomain]/client",
    "purpose": "Interactive page at /sites/[subdomain]/client"
  },
  {
    "path": "/sites/[subdomain]/dashboard",
    "purpose": "Interactive page at /sites/[subdomain]/dashboard"
  },
  {
    "path": "/sites/[subdomain]/history",
    "purpose": "Interactive page at /sites/[subdomain]/history"
  },
  {
    "path": "/sites/[subdomain]/login",
    "purpose": "Interactive page at /sites/[subdomain]/login"
  },
  {
    "path": "/sites/[subdomain]/register",
    "purpose": "Interactive page at /sites/[subdomain]/register"
  },
  {
    "path": "/sites/example-healthy-food",
    "purpose": "Interactive page at /sites/example-healthy-food"
  },
  {
    "path": "/super-admin",
    "purpose": "Interactive page at /super-admin"
  }
] as const;
